url: http://remote.oceandebrant.wp
path: /srv/www/wordpress/htdocs/
user: 1

core config:
  dbname: wp_oceandebrant
  dbuser: oceandebrant
  dbpass: oceandebrant
  dbhost: localhost
  locale: it_IT

core install:
  url: http://remote.oceandebrant.wp
  title: Remote OceanDebrant
  admin_user: oceandebrant
  admin_email: admin@example.org
  admin_password: oceandebrant
