url: http://dev.oceandebrant.wp
path: /srv/www/wordpress/htdocs/

core config:
  dbname: wp_oceandebrant
  dbuser: oceandebrant
  dbpass: oceandebrant
  dbhost: localhost
  locale: it_IT

core install:
  url: http://dev.oceandebrant.wp
  title: OceanDebrant
  admin_user: oceandebrant
  admin_email: admin@example.org
  admin_password: oceandebrant
